config:
  install_tree: 
    root: ~/spack/
    projections:
      all: ${PACKAGE}/${VERSION}/${ARCHITECTURE}-${COMPILERNAME}-${COMPILERVER}-${HASH}
  source_cache: ~/.spack/cache
  binary_index_root: ~/.spack

  # Locations where different types of modules should be installed.
  module_roots:
    tcl: ~/.spack/modules
    lmod: ~/.spack/lmod
