config:
  install_tree: 

    root: ~/.spack/
    projections:
      all: ${PACKAGE}/${VERSION}/${ARCHITECTURE}-${COMPILERNAME}-${COMPILERVER}-${HASH}
  source_cache: ~/.spack/cache

  # Locations where different types of modules should be installed.
  module_roots:
    tcl: ~/.spack/modules
    lmod: ~/.spack/lmod
